# Generated by Django 5.2.7 on 2025-10-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContratos',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_contrato', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'tipo_contratos',
                'managed': False,
            },
        ),
    ]
