# Generated by Django 5.2.7 on 2025-10-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_empresa', models.CharField(max_length=200, unique=True)),
                ('nombre_empresa', models.CharField(max_length=200, unique=True)),
                ('telefono_empresa', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'empresas',
                'managed': False,
            },
        ),
    ]
